### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by JKaiss** [at-internet/piano-analytics-android#1]
Hello, 
when i try to insatiate :
PianoAnalytics pa = PianoAnalytics.getInstance(getApplicationContext());

i get this error systematically : 

error on ConfigStep.loadConfigurationFromLocalFile: java.io.FileNotFoundException: piano-analytics-config.json

i use this documentation : 
https://developers.atinternet-solutions.com/piano-analytics/data-collection/sdks/android-java#integrate-the-library

best regards,
Kais Jaafoura

**Comment by BenDz** [comment]
Hi @JKaiss 
This is a known issue, and we'll fix it later on.

Until then, you can create a `piano-analytics-config.json` file in app assets (`app/src/main/assets/`). Example file content:

```json
{
  "collectEndpoint": "logxxx.xiti.com",
  "siteId": 123456789,
  "pixelPath": "/event",
  "offlineMode": "never",
  "ignoreLimitedAdTracking": false,
  "crashDetection": true,
  "uuidExpirationMode": "fixed",
  "uuidDuration": 365,
  "sessionBackgroundDuration": 30,
  "storeUsers": true,
  "sendWhenOptOut": false,
  "encryptionMode": "IF_COMPATIBLE",
  "visitorIdType": "UUID"
}
```

Regards,
Ben

**Comment by JKaiss** [comment]
when i add the file i had a new error  : 

ConfigurationKeysEnum.fromString : requested value is unknown
