### ISSUE TITLE
Missing Huawei classes in release build

### ISSUE THREAD

**Issue by OndraBasler** [at-internet/piano-analytics-android#12]
I have a problem with SDK in release. In debug the application builds fine. The release build crashes during obfuscation by R8.
I think it is cased by missing Huawei SDK that I haven't added because I don't use Huawei id as visitor ID. Is it really optional or I need to add it even though I don't use it?

Missing class com.huawei.hms.ads.identifier.AdvertisingIdClient$Info (referenced from: io.piano.android.analytics.idproviders.AdvertisingIdInfo io.piano.android.analytics.idproviders.HuaweiAdvertisingIDIdProvider.loadAdvertisingInfo$piano_analytics_release())
Missing class com.huawei.hms.ads.identifier.AdvertisingIdClient (referenced from: io.piano.android.analytics.idproviders.AdvertisingIdInfo io.piano.android.analytics.idproviders.HuaweiAdvertisingIDIdProvider.loadAdvertisingInfo$piano_analytics_release())

I have minimal setup 

```kotlin
val configuration = Configuration.Builder(
     collectDomain = pianoConfiguration.domain,
     site = pianoConfiguration.siteId.toInt(),
).build()

PianoAnalytics.init(application.applicationContext, configuration)
```

**Comment by DeKaN** [comment]
Rules have been released as part of 3.3.4
