### ISSUE TITLE
Piano Analytics SDK Initialization Causing "App Not Responding" Issues

### ISSUE THREAD

**Issue by Titoura** [at-internet/piano-analytics-android#17]
Hi !

We are experiencing issues with the Piano Analytics SDK in our Android application. The SDK requires initialization on the main thread, which can lead to "App Not Responding" (ANR) errors in certain scenarios.

However, the only piece of code which requires access to the main thread seems to be the `lifecycle.addObserver(observer)` part in the SessionStorage. While this method seems quite « light » to perform, the rest of the initialization can be too heavy combined to other SDKs initializations, especially on old/low end devices.

During a progressive rollout, we had about 1000 users experiencing ANRs, which is too much for us. We had to rollback Piano's integration until we find a solution.

Can we consider another approach and execute on the main thread only the method which needs access to it ? 

Thanks

**Comment by DeKaN** [comment]
Hi @Titoura,
Do you initialize SDK in Application class? Can you share number of SDKs, that are initialized by app?

**Comment by Titoura** [comment]
We tend to avoid initializing libraries in the Application class for performance and architectural reasons. And we don't really want our tracking framework to slow down our landing page display. 

For our first deployment, we've used an [Initializer](https://developer.android.com/topic/libraries/app-startup?hl=fr) (from the `androidx.startup` library). 
We thought of initializing Piano lazily to avoid any heavy operation at launch, but combined to our dependency injection tools this is not optimal.

Currently, we have about 20 SDKs being launched using Initializers. But we probably have other ones initialized indirectly (or handled by our dependency injection), which makes it difficult to count (we have a significant codebase).

**Comment by DeKaN** [comment]
Thanks for the information. Initializer uses ContentProvider, which starts before Application class and it's also a good place. 

I'll check possible solutions for allowing initialization on any thread.

**Comment by DeKaN** [comment]
Hi @Titoura,
I've added switching to main thread for `lifecycle.addObserver(observer)`, so now you can try initialize SDK from another thread. It will be part of the next release

**Comment by DeKaN** [comment]
Released with version 3.4.0
