### ISSUE TITLE
Versions <= 3.2: av_position and av_previous_position capped at maxInt for livestreams

### ISSUE THREAD

**Issue by DanielKuhn** [at-internet/piano-analytics-android#18]
When tracking livestream video plays, AV-Playback-time is always zero, because the timestamps of `av_position` and `av_previous_position` options, used to calculate the delta between trackings, are always parsed and handled as `int`. 
Therefore, when both values exceed maxInt, the delta is always zero, resulting in EBVS trackings (AV-Playback-time: 00:00:00.000)

**Comment by BenDz** [comment]
Hi,
If I understand well, you try to use a timestamp as a cursor position. Our processing expects a relative position from the beginning of the playback. Please see our answer there #10 
Don't hesitate to get back should you need.
