### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by RolandMostoha** [at-internet/piano-analytics-android#2]
When can we expect the library to be released in maven central or any public repository? The cloning way is not developer/devops friendly to say the least.

Thanks in advance,
Roland

**Comment by DeKaN** [comment]
Hi @RolandMostoha, it's already in [Maven Central](https://mvnrepository.com/artifact/io.piano/analytics/3.2.1)

**Comment by RolandMostoha** [comment]
Ohh I stuck in the readme, thanks for the link!
